/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:1d26b8f3-1153-49e4-8ef2-397627df968a",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_TtLCJzBi5",
    "aws_user_pools_web_client_id": "6dibjnjtc0lke3p9su3alpvior",
    "oauth": {
        "domain": "tbxproject68de4779-68de4779-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://053eaa88fb024e489ec5b56fbbdf5e05.vfs.cloud9.ap-southeast-1.amazonaws.com/",
        "redirectSignOut": "https://053eaa88fb024e489ec5b56fbbdf5e05.vfs.cloud9.ap-southeast-1.amazonaws.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://bnvqkam4s5hl7nuj6ko4r55qly.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-irjnqfwu2vaylbi3phwucsrnwa",
    "aws_user_files_s3_bucket": "tbxproject75ac4e9c21ff4bec92802ddfbe6b885a84716-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
